from __future__ import annotations

import html
import os
import shutil
from pathlib import Path
from typing import Any


def _to_relative_path(path: str | Path, base_dir: Path) -> str:
    """
    Convert an image path to a relative path from the HTML file directory.
    """
    path = Path(path)
    if not path.is_absolute():
        path = path.resolve()

    base_dir = base_dir.resolve()
    rel_path = os.path.relpath(path, start=base_dir)
    return rel_path.replace("\\", "/")


def save_retrieval_html_report(
    prompts: list[str],
    retrieval_results: list[list[dict[str, Any]]],
    output_html_path: str | Path,
    title: str = "PathVLM-LiteBench Retrieval Report",
    image_width: int = 180,
    copy_images: bool = True,
) -> str:
    """
    Save image-text retrieval results as a simple HTML report.

    Args:
        prompts:
            A list of text prompts.
        retrieval_results:
            A nested list returned by retrieve_topk_images.
            Each result dictionary should contain:
            - index
            - score
            - path
        output_html_path:
            Output HTML file path.
        title:
            HTML report title.
        image_width:
            Display width for each image in pixels.
        copy_images:
            Whether to copy retrieved images to a local assets folder next to
            the HTML report and reference them from there.

    Returns:
        The saved HTML file path as a string.

    Raises:
        ValueError:
            If prompts and retrieval_results have different lengths.
            If any retrieval result does not contain a path.
        FileNotFoundError:
            If copy_images=True and any source image path does not exist.
    """
    if len(prompts) != len(retrieval_results):
        raise ValueError(
            f"prompts and retrieval_results must have the same length: "
            f"{len(prompts)} vs {len(retrieval_results)}"
        )

    output_html_path = Path(output_html_path)
    output_html_path.parent.mkdir(parents=True, exist_ok=True)

    html_dir = output_html_path.parent
    assets_dir = output_html_path.with_name(f"{output_html_path.stem}_assets")
    if copy_images:
        assets_dir.mkdir(parents=True, exist_ok=True)

    escaped_title = html.escape(title)

    html_parts: list[str] = []

    html_parts.append("<!DOCTYPE html>")
    html_parts.append("<html lang='en'>")
    html_parts.append("<head>")
    html_parts.append("  <meta charset='UTF-8'>")
    html_parts.append("  <meta name='viewport' content='width=device-width, initial-scale=1.0'>")
    html_parts.append(f"  <title>{escaped_title}</title>")
    html_parts.append(
        """
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 32px;
      background: #f7f7f7;
      color: #222;
    }
    h1 {
      margin-bottom: 8px;
    }
    .subtitle {
      color: #666;
      margin-bottom: 28px;
    }
    .prompt-section {
      background: #ffffff;
      border-radius: 12px;
      padding: 20px;
      margin-bottom: 24px;
      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
    }
    .prompt-title {
      font-size: 18px;
      font-weight: bold;
      margin-bottom: 16px;
    }
    .grid {
      display: flex;
      flex-wrap: wrap;
      gap: 16px;
    }
    .card {
      width: 220px;
      border: 1px solid #ddd;
      border-radius: 10px;
      padding: 10px;
      background: #fafafa;
    }
    .card img {
      max-width: 100%;
      border-radius: 8px;
      border: 1px solid #ddd;
      background: white;
    }
    .meta {
      font-size: 13px;
      line-height: 1.5;
      margin-top: 8px;
      word-break: break-all;
    }
    .score {
      font-weight: bold;
    }
  </style>
        """
    )
    html_parts.append("</head>")
    html_parts.append("<body>")
    html_parts.append(f"  <h1>{escaped_title}</h1>")
    html_parts.append("  <div class='subtitle'>Generated by PathVLM-LiteBench</div>")

    used_asset_names: set[str] = set()

    for prompt, prompt_results in zip(prompts, retrieval_results):
        html_parts.append("  <div class='prompt-section'>")
        html_parts.append(f"    <div class='prompt-title'>Prompt: {html.escape(prompt)}</div>")
        html_parts.append("    <div class='grid'>")

        for rank, item in enumerate(prompt_results, start=1):
            if "path" not in item:
                raise ValueError("Each retrieval result must contain a 'path' field for HTML report.")

            image_path = item["path"]
            if copy_images:
                source_path = Path(image_path)
                if not source_path.is_absolute():
                    source_path = source_path.resolve()

                if not source_path.exists():
                    raise FileNotFoundError(
                        f"Image path does not exist for HTML report: {source_path}"
                    )

                source_index = item.get("index", "na")
                safe_stem = source_path.stem.replace(" ", "_")
                base_name = f"rank_source_{source_index}_{safe_stem}{source_path.suffix.lower()}"
                candidate_name = base_name
                duplicate_counter = 1
                while candidate_name in used_asset_names:
                    candidate_name = (
                        f"rank_source_{source_index}_{safe_stem}_{duplicate_counter}"
                        f"{source_path.suffix.lower()}"
                    )
                    duplicate_counter += 1

                used_asset_names.add(candidate_name)
                copied_path = assets_dir / candidate_name
                shutil.copy2(source_path, copied_path)

                rel_path = f"{assets_dir.name}/{candidate_name}".replace("\\", "/")
            else:
                rel_path = _to_relative_path(image_path, html_dir)

            index = item.get("index", "N/A")
            score = item.get("score", 0.0)

            html_parts.append("      <div class='card'>")
            html_parts.append(
                f"        <img src='{html.escape(rel_path)}' "
                f"alt='retrieved image {rank}' width='{image_width}'>"
            )
            html_parts.append("        <div class='meta'>")
            html_parts.append(f"          <div><strong>Rank:</strong> {rank}</div>")
            html_parts.append(f"          <div><strong>Index:</strong> {html.escape(str(index))}</div>")
            html_parts.append(f"          <div class='score'>Score: {float(score):.4f}</div>")
            html_parts.append(f"          <div><strong>Path:</strong> {html.escape(str(image_path))}</div>")
            html_parts.append("        </div>")
            html_parts.append("      </div>")

        html_parts.append("    </div>")
        html_parts.append("  </div>")

    html_parts.append("</body>")
    html_parts.append("</html>")

    output_html_path.write_text("\n".join(html_parts), encoding="utf-8")

    return str(output_html_path)
