from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _read_csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as csv_file:
        return list(csv.DictReader(csv_file))


def _format_value(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float):
        return f"{value:.4f}"
    if isinstance(value, Path):
        return value.as_posix()
    if isinstance(value, list):
        return ", ".join(str(item) for item in value)
    if isinstance(value, dict):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return ""
        if "." in text or "e" in text.lower():
            try:
                return f"{float(text):.4f}"
            except ValueError:
                pass
        if "\\" in text and " " not in text:
            return text.replace("\\", "/")
        return text
    return str(value)


def _escape_markdown_cell(value: Any) -> str:
    text = _format_value(value)
    return text.replace("|", "\\|").replace("\n", " ")


def _markdown_table(headers: list[str], rows: list[list[Any]]) -> list[str]:
    lines = [
        "| " + " | ".join(_escape_markdown_cell(header) for header in headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(_escape_markdown_cell(cell) for cell in row) + " |")
    return lines


def _distribution_rows(distribution: dict[str, Any]) -> list[list[Any]]:
    rows = [[label, count] for label, count in distribution.items()]
    return sorted(rows, key=lambda row: str(row[0]))


def _format_distribution(distribution: Any) -> str:
    if not isinstance(distribution, dict) or not distribution:
        return ""
    return ", ".join(
        f"{label}={count}"
        for label, count in sorted(distribution.items(), key=lambda item: str(item[0]))
    )


def _is_truthy_text(value: str) -> bool:
    return value.strip().lower() in {"true", "1", "yes"}


def _run_label(report_dir: Path, index: int, run_names: list[str] | None) -> str:
    if run_names is not None and index < len(run_names):
        run_name = run_names[index].strip()
        if run_name:
            return run_name
    return report_dir.name or f"run_{index + 1}"


def _require_run_name_count(report_dirs: list[Path], run_names: list[str] | None) -> None:
    if run_names is not None and len(run_names) != len(report_dirs):
        raise ValueError(
            "run_names must contain exactly one label per report directory."
        )


def _mean_numeric(values: list[Any]) -> float | None:
    numeric_values: list[float] = []
    for value in values:
        if value is None:
            continue
        try:
            numeric_values.append(float(value))
        except (TypeError, ValueError):
            continue
    if not numeric_values:
        return None
    return sum(numeric_values) / len(numeric_values)


def _metric_sort_key(metric_name: str) -> tuple[str, int | str]:
    prefix, separator, suffix = metric_name.partition("@")
    if separator and suffix.isdigit():
        return (prefix, int(suffix))
    return (metric_name, metric_name)


def build_zero_shot_experiment_summary(report_dir: str | Path) -> str:
    """
    Build a Markdown summary from a zero-shot report directory.

    The expected report artifacts are generated by
    `examples/02_zero_shot_classification_demo.py --save_report`.
    """
    report_dir = Path(report_dir)
    metrics_path = report_dir / "metrics.json"
    predictions_path = report_dir / "predictions.csv"
    errors_path = report_dir / "errors.csv"

    if not metrics_path.exists():
        raise FileNotFoundError(f"Missing zero-shot metrics file: {metrics_path}")

    payload = _read_json(metrics_path)
    metadata = payload.get("metadata", {})
    metrics = payload.get("metrics", {})
    classification_report = metrics.get("classification_report")
    error_summary = metrics.get("error_summary", {})

    predictions_rows = _read_csv_rows(predictions_path) if predictions_path.exists() else []
    errors_rows = _read_csv_rows(errors_path) if errors_path.exists() else []
    num_predictions = len(predictions_rows)
    num_errors_csv = len(errors_rows)

    lines: list[str] = [
        "# Zero-Shot Experiment Summary",
        "",
        "This summary was generated from PathVLM-LiteBench zero-shot report artifacts.",
        "It is intended for lightweight model-behavior review, not clinical interpretation.",
        "",
        "## Run Metadata",
        "",
    ]

    metadata_rows = [
        ["Model", metadata.get("model")],
        ["Device", metadata.get("device")],
        ["Split", metadata.get("split")],
        ["Manifest", metadata.get("manifest")],
        ["Image directory", metadata.get("image_dir")],
        ["Class names", metadata.get("class_names")],
        ["Top-k", metadata.get("top_k")],
        ["Number of images", metadata.get("num_images")],
    ]
    lines.extend(_markdown_table(["Field", "Value"], metadata_rows))
    lines.append("")

    if isinstance(classification_report, dict) and classification_report:
        lines.extend(
            [
                "## Aggregate Metrics",
                "",
            ]
        )
        metric_rows = [
            ["Accuracy", classification_report.get("accuracy")],
            ["Balanced accuracy", classification_report.get("balanced_accuracy")],
            ["Macro precision", classification_report.get("macro_precision")],
            ["Macro recall", classification_report.get("macro_recall")],
            ["Macro F1", classification_report.get("macro_f1")],
        ]
        lines.extend(_markdown_table(["Metric", "Value"], metric_rows))
        lines.append("")

        per_class = classification_report.get("per_class", {})
        if isinstance(per_class, dict) and per_class:
            lines.extend(
                [
                    "## Per-Class Metrics",
                    "",
                ]
            )
            per_class_rows = []
            for class_name, class_metrics in per_class.items():
                per_class_rows.append(
                    [
                        class_name,
                        class_metrics.get("precision"),
                        class_metrics.get("recall"),
                        class_metrics.get("f1"),
                        class_metrics.get("support"),
                    ]
                )
            lines.extend(
                _markdown_table(
                    ["Class", "Precision", "Recall", "F1", "Support"],
                    per_class_rows,
                )
            )
            lines.append("")

        confusion = classification_report.get("confusion_matrix", {})
        if isinstance(confusion, dict) and confusion.get("class_names") and confusion.get("matrix"):
            class_names = confusion["class_names"]
            matrix = confusion["matrix"]
            lines.extend(
                [
                    "## Confusion Matrix",
                    "",
                ]
            )
            confusion_rows = [
                [true_class_name, *row]
                for true_class_name, row in zip(class_names, matrix)
            ]
            lines.extend(_markdown_table(["True \\ Pred", *class_names], confusion_rows))
            lines.append("")
    else:
        lines.extend(
            [
                "## Aggregate Metrics",
                "",
                "Classification metrics were not available, likely because labels were missing.",
                "",
            ]
        )

    if isinstance(error_summary, dict) and error_summary:
        lines.extend(
            [
                "## Label Distributions",
                "",
            ]
        )
        true_distribution = error_summary.get("true_label_distribution", {})
        predicted_distribution = error_summary.get("predicted_label_distribution", {})

        if isinstance(true_distribution, dict) and true_distribution:
            lines.extend(["### True Labels", ""])
            lines.extend(_markdown_table(["Label", "Count"], _distribution_rows(true_distribution)))
            lines.append("")

        if isinstance(predicted_distribution, dict) and predicted_distribution:
            lines.extend(["### Predicted Labels", ""])
            lines.extend(
                _markdown_table(["Label", "Count"], _distribution_rows(predicted_distribution))
            )
            lines.append("")

        lines.extend(["## Error Analysis", ""])
        error_rows = [
            ["Labeled samples", error_summary.get("labeled_count")],
            ["Unlabeled samples", error_summary.get("unlabeled_count")],
            ["Errors", error_summary.get("num_errors")],
            ["Error rate", error_summary.get("error_rate")],
        ]
        lines.extend(_markdown_table(["Field", "Value"], error_rows))
        lines.append("")

        warning = error_summary.get("warning")
        if isinstance(warning, str) and warning:
            lines.extend(["## Warning", "", warning, ""])

    lines.extend(
        [
            "## Artifacts",
            "",
        ]
    )
    artifact_rows = [
        ["metrics.json", "found", metrics_path],
        [
            "predictions.csv",
            f"found ({num_predictions} rows)" if predictions_path.exists() else "missing",
            predictions_path,
        ],
        [
            "errors.csv",
            f"found ({num_errors_csv} rows)" if errors_path.exists() else "missing",
            errors_path,
        ],
    ]
    lines.extend(_markdown_table(["File", "Status", "Path"], artifact_rows))
    lines.append("")

    return "\n".join(lines)


def build_retrieval_experiment_summary(report_dir: str | Path) -> str:
    """
    Build a Markdown summary from a retrieval report directory.

    The expected report artifacts are generated by
    `examples/01_patch_text_retrieval_demo.py --save_report`.
    """
    report_dir = Path(report_dir)
    metrics_path = report_dir / "retrieval_metrics.json"
    results_path = report_dir / "retrieval_results.csv"

    if not metrics_path.exists():
        raise FileNotFoundError(f"Missing retrieval metrics file: {metrics_path}")

    payload = _read_json(metrics_path)
    metadata = payload.get("metadata", {})
    metrics = payload.get("metrics", {})

    results_rows = _read_csv_rows(results_path) if results_path.exists() else []
    positive_rows = [
        row for row in results_rows if _is_truthy_text(str(row.get("is_positive", "")))
    ]
    prompt_indices = {
        row.get("prompt_index", "")
        for row in results_rows
        if row.get("prompt_index", "") != ""
    }

    lines: list[str] = [
        "# Retrieval Experiment Summary",
        "",
        "This summary was generated from PathVLM-LiteBench retrieval report artifacts.",
        "It is intended for lightweight patch-level retrieval review, not clinical interpretation.",
        "",
        "## Run Metadata",
        "",
    ]

    metadata_rows = [
        ["Model", metadata.get("model")],
        ["Device", metadata.get("device")],
        ["Split", metadata.get("split")],
        ["Manifest", metadata.get("manifest")],
        ["Image root", metadata.get("image_root")],
        ["Image directory", metadata.get("image_dir")],
        ["Top-k", metadata.get("top_k")],
        ["Recall@K values", metadata.get("recall_k")],
        ["Number of images", metadata.get("num_images")],
        ["Number of prompts", metadata.get("num_prompts")],
    ]
    lines.extend(_markdown_table(["Field", "Value"], metadata_rows))
    lines.append("")

    prompts = metadata.get("prompts")
    label_prompts = metadata.get("label_prompts")
    if isinstance(prompts, list) and prompts:
        lines.extend(["## Prompts", ""])
        prompt_rows = []
        for idx, prompt in enumerate(prompts):
            target_label = ""
            if isinstance(label_prompts, list) and idx < len(label_prompts):
                target_label = label_prompts[idx]
            prompt_rows.append([idx, prompt, target_label])
        lines.extend(_markdown_table(["Index", "Prompt", "Target label"], prompt_rows))
        lines.append("")

    recall_at_k = metrics.get("recall_at_k")
    mean_recall = metrics.get("mean_recall")
    if isinstance(recall_at_k, dict) and recall_at_k:
        lines.extend(["## Retrieval Metrics", ""])
        metric_rows = [[metric_name, metric_value] for metric_name, metric_value in recall_at_k.items()]
        if mean_recall is not None:
            metric_rows.append(["Mean recall", mean_recall])
        lines.extend(_markdown_table(["Metric", "Value"], metric_rows))
        lines.append("")
    else:
        lines.extend(
            [
                "## Retrieval Metrics",
                "",
                str(
                    metrics.get(
                        "note",
                        "Recall@K metrics were not available in this report.",
                    )
                ),
                "",
            ]
        )

    lines.extend(["## Retrieval Rows", ""])
    result_rows = [
        ["Result rows", len(results_rows)],
        ["Prompts in CSV", len(prompt_indices)],
        ["Positive rows", len(positive_rows)],
    ]
    lines.extend(_markdown_table(["Field", "Value"], result_rows))
    lines.append("")

    lines.extend(["## Artifacts", ""])
    artifact_rows = [
        ["retrieval_metrics.json", "found", metrics_path],
        [
            "retrieval_results.csv",
            f"found ({len(results_rows)} rows)" if results_path.exists() else "missing",
            results_path,
        ],
    ]
    lines.extend(_markdown_table(["File", "Status", "Path"], artifact_rows))
    lines.append("")

    return "\n".join(lines)


def build_prompt_sensitivity_experiment_summary(report_dir: str | Path) -> str:
    """
    Build a Markdown summary from a prompt sensitivity report directory.

    The expected report artifacts are generated by
    `examples/03_prompt_sensitivity_demo.py --save_report`.
    """
    report_dir = Path(report_dir)
    metrics_path = report_dir / "prompt_sensitivity_metrics.json"
    summary_path = report_dir / "prompt_sensitivity_summary.csv"
    details_path = report_dir / "prompt_sensitivity_details.csv"

    if not metrics_path.exists():
        raise FileNotFoundError(f"Missing prompt sensitivity metrics file: {metrics_path}")

    payload = _read_json(metrics_path)
    metadata = payload.get("metadata", {})
    results = payload.get("results", [])

    summary_rows = _read_csv_rows(summary_path) if summary_path.exists() else []
    details_rows = _read_csv_rows(details_path) if details_path.exists() else []
    concepts_in_details = {
        row.get("concept_name", "")
        for row in details_rows
        if row.get("concept_name", "") != ""
    }
    prompt_keys = {
        (row.get("concept_name", ""), row.get("prompt_index", ""))
        for row in details_rows
        if row.get("concept_name", "") != "" and row.get("prompt_index", "") != ""
    }

    lines: list[str] = [
        "# Prompt Sensitivity Experiment Summary",
        "",
        "This summary was generated from PathVLM-LiteBench prompt sensitivity report artifacts.",
        "It is intended for lightweight prompt-behavior review, not clinical interpretation.",
        "",
        "## Run Metadata",
        "",
    ]

    metadata_rows = [
        ["Model", metadata.get("model")],
        ["Device", metadata.get("device")],
        ["Image directory", metadata.get("image_dir")],
        ["Top-k", metadata.get("top_k")],
        ["Use pathology prompts", metadata.get("use_pathology_prompts")],
        ["Concepts", metadata.get("concepts")],
        ["Number of images", metadata.get("num_images")],
        ["Number of concepts", metadata.get("num_concepts")],
    ]
    lines.extend(_markdown_table(["Field", "Value"], metadata_rows))
    lines.append("")

    if summary_rows:
        lines.extend(["## Concept Summary", ""])
        concept_rows = []
        for row in summary_rows:
            concept_rows.append(
                [
                    row.get("concept_name", ""),
                    row.get("num_prompts", ""),
                    row.get("mean_topk_overlap", ""),
                    row.get("mean_similarity_std", ""),
                ]
            )
        lines.extend(
            _markdown_table(
                [
                    "Concept",
                    "Num prompts",
                    "Mean top-k overlap",
                    "Mean similarity std",
                ],
                concept_rows,
            )
        )
        lines.append("")
        lines.extend(
            [
                "Higher mean top-k overlap indicates that prompt variants retrieved more similar top-k image sets.",
                "",
            ]
        )
    elif isinstance(results, list) and results:
        lines.extend(["## Concept Summary", ""])
        concept_rows = []
        for item in results:
            if not isinstance(item, dict):
                continue
            concept_rows.append(
                [
                    item.get("concept_name", ""),
                    item.get("num_prompts", ""),
                    item.get("mean_topk_overlap", ""),
                    item.get("mean_similarity_std", ""),
                ]
            )
        lines.extend(
            _markdown_table(
                [
                    "Concept",
                    "Num prompts",
                    "Mean top-k overlap",
                    "Mean similarity std",
                ],
                concept_rows,
            )
        )
        lines.append("")
        lines.extend(
            [
                "Higher mean top-k overlap indicates that prompt variants retrieved more similar top-k image sets.",
                "",
            ]
        )
    else:
        lines.extend(
            [
                "## Concept Summary",
                "",
                "Prompt sensitivity summary metrics were not available in this report.",
                "",
            ]
        )

    lines.extend(["## Prompt Detail Rows", ""])
    detail_rows = [
        ["Summary rows", len(summary_rows)],
        ["Detail rows", len(details_rows)],
        ["Concepts in details", len(concepts_in_details)],
        ["Prompt variants in details", len(prompt_keys)],
    ]
    lines.extend(_markdown_table(["Field", "Value"], detail_rows))
    lines.append("")

    lines.extend(["## Artifacts", ""])
    artifact_rows = [
        ["prompt_sensitivity_metrics.json", "found", metrics_path],
        [
            "prompt_sensitivity_summary.csv",
            f"found ({len(summary_rows)} rows)" if summary_path.exists() else "missing",
            summary_path,
        ],
        [
            "prompt_sensitivity_details.csv",
            f"found ({len(details_rows)} rows)" if details_path.exists() else "missing",
            details_path,
        ],
    ]
    lines.extend(_markdown_table(["File", "Status", "Path"], artifact_rows))
    lines.append("")

    return "\n".join(lines)


def build_zero_shot_comparison_summary(
    report_dirs: list[str | Path],
    run_names: list[str] | None = None,
) -> str:
    """
    Build a Markdown comparison summary for multiple zero-shot report directories.
    """
    resolved_report_dirs = [Path(report_dir) for report_dir in report_dirs]
    if not resolved_report_dirs:
        raise ValueError("At least one report directory is required.")
    _require_run_name_count(resolved_report_dirs, run_names)

    rows: list[list[Any]] = []
    artifact_rows: list[list[Any]] = []

    for index, report_dir in enumerate(resolved_report_dirs):
        metrics_path = report_dir / "metrics.json"
        predictions_path = report_dir / "predictions.csv"
        errors_path = report_dir / "errors.csv"
        if not metrics_path.exists():
            raise FileNotFoundError(f"Missing zero-shot metrics file: {metrics_path}")

        payload = _read_json(metrics_path)
        metadata = payload.get("metadata", {})
        metrics = payload.get("metrics", {})
        classification_report = metrics.get("classification_report", {})
        error_summary = metrics.get("error_summary", {})

        if not isinstance(classification_report, dict):
            classification_report = {}
        if not isinstance(error_summary, dict):
            error_summary = {}

        rows.append(
            [
                _run_label(report_dir, index, run_names),
                metadata.get("model"),
                metadata.get("split"),
                metadata.get("num_images"),
                classification_report.get("accuracy"),
                classification_report.get("balanced_accuracy"),
                classification_report.get("macro_f1"),
                error_summary.get("num_errors"),
                error_summary.get("error_rate"),
                _format_distribution(error_summary.get("predicted_label_distribution")),
                error_summary.get("warning"),
            ]
        )
        artifact_rows.append(
            [
                _run_label(report_dir, index, run_names),
                metrics_path,
                "found" if predictions_path.exists() else "missing",
                "found" if errors_path.exists() else "missing",
            ]
        )

    lines: list[str] = [
        "# Zero-Shot Comparison Summary",
        "",
        "This summary compares saved PathVLM-LiteBench zero-shot report artifacts.",
        "It is intended for lightweight model-behavior review, not clinical interpretation.",
        "",
        "## Run Comparison",
        "",
    ]
    lines.extend(
        _markdown_table(
            [
                "Run",
                "Model",
                "Split",
                "Images",
                "Accuracy",
                "Balanced accuracy",
                "Macro F1",
                "Errors",
                "Error rate",
                "Predicted distribution",
                "Warning",
            ],
            rows,
        )
    )
    lines.extend(
        [
            "",
            "## Artifacts",
            "",
        ]
    )
    lines.extend(
        _markdown_table(
            ["Run", "metrics.json", "predictions.csv", "errors.csv"],
            artifact_rows,
        )
    )
    lines.append("")
    return "\n".join(lines)


def build_retrieval_comparison_summary(
    report_dirs: list[str | Path],
    run_names: list[str] | None = None,
) -> str:
    """
    Build a Markdown comparison summary for multiple retrieval report directories.
    """
    resolved_report_dirs = [Path(report_dir) for report_dir in report_dirs]
    if not resolved_report_dirs:
        raise ValueError("At least one report directory is required.")
    _require_run_name_count(resolved_report_dirs, run_names)

    payloads: list[tuple[str, Path, dict[str, Any], Path]] = []
    recall_keys: set[str] = set()
    for index, report_dir in enumerate(resolved_report_dirs):
        metrics_path = report_dir / "retrieval_metrics.json"
        results_path = report_dir / "retrieval_results.csv"
        if not metrics_path.exists():
            raise FileNotFoundError(f"Missing retrieval metrics file: {metrics_path}")

        payload = _read_json(metrics_path)
        metrics = payload.get("metrics", {})
        recall_at_k = metrics.get("recall_at_k", {})
        if isinstance(recall_at_k, dict):
            recall_keys.update(str(key) for key in recall_at_k)
        payloads.append(
            (
                _run_label(report_dir, index, run_names),
                report_dir,
                payload,
                results_path,
            )
        )

    sorted_recall_keys = sorted(recall_keys, key=_metric_sort_key)
    rows: list[list[Any]] = []
    artifact_rows: list[list[Any]] = []
    for run_label, report_dir, payload, results_path in payloads:
        metadata = payload.get("metadata", {})
        metrics = payload.get("metrics", {})
        recall_at_k = metrics.get("recall_at_k", {})
        if not isinstance(recall_at_k, dict):
            recall_at_k = {}

        rows.append(
            [
                run_label,
                metadata.get("model"),
                metadata.get("split"),
                metadata.get("num_images"),
                metadata.get("num_prompts"),
                *[recall_at_k.get(key) for key in sorted_recall_keys],
                metrics.get("mean_recall"),
                metrics.get("note"),
            ]
        )
        artifact_rows.append(
            [
                run_label,
                report_dir / "retrieval_metrics.json",
                "found" if results_path.exists() else "missing",
            ]
        )

    lines: list[str] = [
        "# Retrieval Comparison Summary",
        "",
        "This summary compares saved PathVLM-LiteBench retrieval report artifacts.",
        "It is intended for lightweight patch-level retrieval review, not clinical interpretation.",
        "",
        "## Run Comparison",
        "",
    ]
    lines.extend(
        _markdown_table(
            [
                "Run",
                "Model",
                "Split",
                "Images",
                "Prompts",
                *sorted_recall_keys,
                "Mean recall",
                "Note",
            ],
            rows,
        )
    )
    lines.extend(["", "## Artifacts", ""])
    lines.extend(
        _markdown_table(
            ["Run", "retrieval_metrics.json", "retrieval_results.csv"],
            artifact_rows,
        )
    )
    lines.append("")
    return "\n".join(lines)


def build_prompt_sensitivity_comparison_summary(
    report_dirs: list[str | Path],
    run_names: list[str] | None = None,
) -> str:
    """
    Build a Markdown comparison summary for multiple prompt sensitivity reports.
    """
    resolved_report_dirs = [Path(report_dir) for report_dir in report_dirs]
    if not resolved_report_dirs:
        raise ValueError("At least one report directory is required.")
    _require_run_name_count(resolved_report_dirs, run_names)

    rows: list[list[Any]] = []
    artifact_rows: list[list[Any]] = []
    for index, report_dir in enumerate(resolved_report_dirs):
        metrics_path = report_dir / "prompt_sensitivity_metrics.json"
        summary_path = report_dir / "prompt_sensitivity_summary.csv"
        details_path = report_dir / "prompt_sensitivity_details.csv"
        if not metrics_path.exists():
            raise FileNotFoundError(
                f"Missing prompt sensitivity metrics file: {metrics_path}"
            )

        payload = _read_json(metrics_path)
        metadata = payload.get("metadata", {})
        results = payload.get("results", [])
        if not isinstance(results, list):
            results = []

        topk_values = [
            item.get("mean_topk_overlap")
            for item in results
            if isinstance(item, dict)
        ]
        std_values = [
            item.get("mean_similarity_std")
            for item in results
            if isinstance(item, dict)
        ]

        rows.append(
            [
                _run_label(report_dir, index, run_names),
                metadata.get("model"),
                metadata.get("num_images"),
                metadata.get("num_concepts"),
                _mean_numeric(topk_values),
                _mean_numeric(std_values),
                metadata.get("use_pathology_prompts"),
            ]
        )
        artifact_rows.append(
            [
                _run_label(report_dir, index, run_names),
                metrics_path,
                "found" if summary_path.exists() else "missing",
                "found" if details_path.exists() else "missing",
            ]
        )

    lines: list[str] = [
        "# Prompt Sensitivity Comparison Summary",
        "",
        "This summary compares saved PathVLM-LiteBench prompt sensitivity artifacts.",
        "It is intended for lightweight prompt-behavior review, not clinical interpretation.",
        "",
        "## Run Comparison",
        "",
    ]
    lines.extend(
        _markdown_table(
            [
                "Run",
                "Model",
                "Images",
                "Concepts",
                "Mean top-k overlap",
                "Mean similarity std",
                "Use pathology prompts",
            ],
            rows,
        )
    )
    lines.extend(
        [
            "",
            "Mean top-k overlap and mean similarity std are averaged across concepts.",
            "",
            "## Artifacts",
            "",
        ]
    )
    lines.extend(
        _markdown_table(
            [
                "Run",
                "prompt_sensitivity_metrics.json",
                "prompt_sensitivity_summary.csv",
                "prompt_sensitivity_details.csv",
            ],
            artifact_rows,
        )
    )
    lines.append("")
    return "\n".join(lines)


def build_experiment_comparison_summary(
    task: str,
    report_dirs: list[str | Path],
    run_names: list[str] | None = None,
) -> str:
    """
    Build a Markdown comparison summary for multiple report directories.
    """
    if task == "zero-shot":
        return build_zero_shot_comparison_summary(report_dirs, run_names)
    if task == "retrieval":
        return build_retrieval_comparison_summary(report_dirs, run_names)
    if task == "prompt-sensitivity":
        return build_prompt_sensitivity_comparison_summary(report_dirs, run_names)
    raise ValueError(f"Unsupported comparison task: {task}")


def save_zero_shot_experiment_summary(
    report_dir: str | Path,
    output_path: str | Path | None = None,
) -> str:
    """
    Save a Markdown summary for a zero-shot report directory.
    """
    report_dir = Path(report_dir)
    output_path = Path(output_path) if output_path is not None else report_dir / "experiment_summary.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        build_zero_shot_experiment_summary(report_dir),
        encoding="utf-8",
    )
    return str(output_path)


def save_prompt_sensitivity_experiment_summary(
    report_dir: str | Path,
    output_path: str | Path | None = None,
) -> str:
    """
    Save a Markdown summary for a prompt sensitivity report directory.
    """
    report_dir = Path(report_dir)
    output_path = Path(output_path) if output_path is not None else report_dir / "experiment_summary.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        build_prompt_sensitivity_experiment_summary(report_dir),
        encoding="utf-8",
    )
    return str(output_path)


def save_retrieval_experiment_summary(
    report_dir: str | Path,
    output_path: str | Path | None = None,
) -> str:
    """
    Save a Markdown summary for a retrieval report directory.
    """
    report_dir = Path(report_dir)
    output_path = Path(output_path) if output_path is not None else report_dir / "experiment_summary.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        build_retrieval_experiment_summary(report_dir),
        encoding="utf-8",
    )
    return str(output_path)


def save_experiment_comparison_summary(
    task: str,
    report_dirs: list[str | Path],
    output_path: str | Path,
    run_names: list[str] | None = None,
) -> str:
    """
    Save a Markdown comparison summary for multiple report directories.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        build_experiment_comparison_summary(task, report_dirs, run_names),
        encoding="utf-8",
    )
    return str(output_path)
