from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _read_csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as csv_file:
        return list(csv.DictReader(csv_file))


def _format_value(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float):
        return f"{value:.4f}"
    if isinstance(value, list):
        return ", ".join(str(item) for item in value)
    if isinstance(value, dict):
        return json.dumps(value, ensure_ascii=False)
    return str(value)


def _escape_markdown_cell(value: Any) -> str:
    text = _format_value(value)
    return text.replace("|", "\\|").replace("\n", " ")


def _markdown_table(headers: list[str], rows: list[list[Any]]) -> list[str]:
    lines = [
        "| " + " | ".join(_escape_markdown_cell(header) for header in headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(_escape_markdown_cell(cell) for cell in row) + " |")
    return lines


def _distribution_rows(distribution: dict[str, Any]) -> list[list[Any]]:
    rows = [[label, count] for label, count in distribution.items()]
    return sorted(rows, key=lambda row: str(row[0]))


def build_zero_shot_experiment_summary(report_dir: str | Path) -> str:
    """
    Build a Markdown summary from a zero-shot report directory.

    The expected report artifacts are generated by
    `examples/02_zero_shot_classification_demo.py --save_report`.
    """
    report_dir = Path(report_dir)
    metrics_path = report_dir / "metrics.json"
    predictions_path = report_dir / "predictions.csv"
    errors_path = report_dir / "errors.csv"

    if not metrics_path.exists():
        raise FileNotFoundError(f"Missing zero-shot metrics file: {metrics_path}")

    payload = _read_json(metrics_path)
    metadata = payload.get("metadata", {})
    metrics = payload.get("metrics", {})
    classification_report = metrics.get("classification_report")
    error_summary = metrics.get("error_summary", {})

    predictions_rows = _read_csv_rows(predictions_path) if predictions_path.exists() else []
    errors_rows = _read_csv_rows(errors_path) if errors_path.exists() else []
    num_predictions = len(predictions_rows)
    num_errors_csv = len(errors_rows)

    lines: list[str] = [
        "# Zero-Shot Experiment Summary",
        "",
        "This summary was generated from PathVLM-LiteBench zero-shot report artifacts.",
        "It is intended for lightweight model-behavior review, not clinical interpretation.",
        "",
        "## Run Metadata",
        "",
    ]

    metadata_rows = [
        ["Model", metadata.get("model")],
        ["Device", metadata.get("device")],
        ["Split", metadata.get("split")],
        ["Manifest", metadata.get("manifest")],
        ["Image directory", metadata.get("image_dir")],
        ["Class names", metadata.get("class_names")],
        ["Top-k", metadata.get("top_k")],
        ["Number of images", metadata.get("num_images")],
    ]
    lines.extend(_markdown_table(["Field", "Value"], metadata_rows))
    lines.append("")

    if isinstance(classification_report, dict) and classification_report:
        lines.extend(
            [
                "## Aggregate Metrics",
                "",
            ]
        )
        metric_rows = [
            ["Accuracy", classification_report.get("accuracy")],
            ["Balanced accuracy", classification_report.get("balanced_accuracy")],
            ["Macro precision", classification_report.get("macro_precision")],
            ["Macro recall", classification_report.get("macro_recall")],
            ["Macro F1", classification_report.get("macro_f1")],
        ]
        lines.extend(_markdown_table(["Metric", "Value"], metric_rows))
        lines.append("")

        per_class = classification_report.get("per_class", {})
        if isinstance(per_class, dict) and per_class:
            lines.extend(
                [
                    "## Per-Class Metrics",
                    "",
                ]
            )
            per_class_rows = []
            for class_name, class_metrics in per_class.items():
                per_class_rows.append(
                    [
                        class_name,
                        class_metrics.get("precision"),
                        class_metrics.get("recall"),
                        class_metrics.get("f1"),
                        class_metrics.get("support"),
                    ]
                )
            lines.extend(
                _markdown_table(
                    ["Class", "Precision", "Recall", "F1", "Support"],
                    per_class_rows,
                )
            )
            lines.append("")

        confusion = classification_report.get("confusion_matrix", {})
        if isinstance(confusion, dict) and confusion.get("class_names") and confusion.get("matrix"):
            class_names = confusion["class_names"]
            matrix = confusion["matrix"]
            lines.extend(
                [
                    "## Confusion Matrix",
                    "",
                ]
            )
            confusion_rows = [
                [true_class_name, *row]
                for true_class_name, row in zip(class_names, matrix)
            ]
            lines.extend(_markdown_table(["True \\ Pred", *class_names], confusion_rows))
            lines.append("")
    else:
        lines.extend(
            [
                "## Aggregate Metrics",
                "",
                "Classification metrics were not available, likely because labels were missing.",
                "",
            ]
        )

    if isinstance(error_summary, dict) and error_summary:
        lines.extend(
            [
                "## Label Distributions",
                "",
            ]
        )
        true_distribution = error_summary.get("true_label_distribution", {})
        predicted_distribution = error_summary.get("predicted_label_distribution", {})

        if isinstance(true_distribution, dict) and true_distribution:
            lines.extend(["### True Labels", ""])
            lines.extend(_markdown_table(["Label", "Count"], _distribution_rows(true_distribution)))
            lines.append("")

        if isinstance(predicted_distribution, dict) and predicted_distribution:
            lines.extend(["### Predicted Labels", ""])
            lines.extend(
                _markdown_table(["Label", "Count"], _distribution_rows(predicted_distribution))
            )
            lines.append("")

        lines.extend(["## Error Analysis", ""])
        error_rows = [
            ["Labeled samples", error_summary.get("labeled_count")],
            ["Unlabeled samples", error_summary.get("unlabeled_count")],
            ["Errors", error_summary.get("num_errors")],
            ["Error rate", error_summary.get("error_rate")],
        ]
        lines.extend(_markdown_table(["Field", "Value"], error_rows))
        lines.append("")

        warning = error_summary.get("warning")
        if isinstance(warning, str) and warning:
            lines.extend(["## Warning", "", warning, ""])

    lines.extend(
        [
            "## Artifacts",
            "",
        ]
    )
    artifact_rows = [
        ["metrics.json", "found", metrics_path],
        [
            "predictions.csv",
            f"found ({num_predictions} rows)" if predictions_path.exists() else "missing",
            predictions_path,
        ],
        [
            "errors.csv",
            f"found ({num_errors_csv} rows)" if errors_path.exists() else "missing",
            errors_path,
        ],
    ]
    lines.extend(_markdown_table(["File", "Status", "Path"], artifact_rows))
    lines.append("")

    return "\n".join(lines)


def save_zero_shot_experiment_summary(
    report_dir: str | Path,
    output_path: str | Path | None = None,
) -> str:
    """
    Save a Markdown summary for a zero-shot report directory.
    """
    report_dir = Path(report_dir)
    output_path = Path(output_path) if output_path is not None else report_dir / "experiment_summary.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        build_zero_shot_experiment_summary(report_dir),
        encoding="utf-8",
    )
    return str(output_path)
